// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrlxNwXqbuUgC1cmg_rjb5s2Jx0c1XPUI',
    appId: '1:392649198626:web:a33c9893ef7717915a8e7b',
    messagingSenderId: '392649198626',
    projectId: 'dish-adding',
    authDomain: 'dish-adding.firebaseapp.com',
    storageBucket: 'dish-adding.appspot.com',
    measurementId: 'G-BD8S3ZBJQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUc_qf9eK_vVCAunpqTng8SPfomNOShFI',
    appId: '1:392649198626:android:67c2ddbca0b5d2295a8e7b',
    messagingSenderId: '392649198626',
    projectId: 'dish-adding',
    storageBucket: 'dish-adding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQzs1gQra2c-v3ktOZUQKsU5WZHaYrd4',
    appId: '1:392649198626:ios:714b0d132c4647fe5a8e7b',
    messagingSenderId: '392649198626',
    projectId: 'dish-adding',
    storageBucket: 'dish-adding.appspot.com',
    iosBundleId: 'com.example.madFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQzs1gQra2c-v3ktOZUQKsU5WZHaYrd4',
    appId: '1:392649198626:ios:292fb8c518b2e5495a8e7b',
    messagingSenderId: '392649198626',
    projectId: 'dish-adding',
    storageBucket: 'dish-adding.appspot.com',
    iosBundleId: 'com.example.madFinal.RunnerTests',
  );
}
